
rcat <- function(n, prob) {
   ## Categorical random variables.
   ## n      number of variables to generate
   ## prob   probabilities.  Either NxM matrix -- each row corresponds to the probabilities
   ##        of the corresponding draw, or a vector -- equal probabilities for all the draws. 
   ##        The probabilities will be normalized to sum to unity by draws.
   ## 
   ## Generates a vector of length N of multinomial variables.
   ## The probabilities may differ for each component.
   ## The rows of probabilities should sum to less than one, runif
   ## will be split according to the intervals, generated by
   ## probabilities.
   if(is.null(dim(prob))) {
      prob <- matrix(prob, n, length(prob), byrow=TRUE)
   }
   prob <- prob/rowSums(prob)
   storage.mode(prob) <- "double"
   r <- .Call("do_rcat", prob, PACKAGE="econMisc")
   r
}    
